# Generated by Django 3.0.3 on 2021-09-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210904_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Society'),
            preserve_default=False,
        ),
    ]
